### ISSUE TITLE
Time zone

### ISSUE THREAD

**Issue by ifuchs** [ish-app/ish#1086]
What is the easiest way to change (in a persistent way) the time zone which defaults to UTC?

**Comment by emkey1** [comment]
This is actually a bug in 32 bit versions of Alpine.  It requires either a patch to musl I believe or recompiling the timezone libraries.  You also have to make a link to the correct timezone file.  That link is in /etc/localtime.

The latest version of my custom image is fixed.  I also published a script as well as the recompiled timezone files on my Discord chat. (https://discord.gg/RkdBXHMbgc)

There was an issue open for this previously, but it was closed when it was determined the issue was not iSH specific.

**Comment by ifuchs** [comment]
Is there a way I can access your custom image? (I went to the link but I'm not sure where to find the image for download).

**Comment by emkey1** [comment]
Sure, look in the #aok-builds channel.  The latest is Alpha .55

**Comment by emkey1** [comment]
If you look in #aok-goodies you can find a shell script along with the 'fixed' timezone files.  Save them in the same directory on iSH and run the shell script as root.  It will overwrite the 'broken' timezone files.

'broken' and 'fixed' are in quotes as there is really nothing wrong with the timezone files.  There are two different formats, a small and a large one.  The musl library is apparently incompatible currently with the small format which is what Alpine normally ships with.  My files are the fat version.  They are a couple hundred K or so larger than the small ones but musl works properly with them.

**Comment by DannyQuah** [comment]
Thank you so much for this. I wonder if it's worth pointing out that even on the `iSH` I installed this month (Jan 2022) from the AppStore, the default is still to run on UTC. To fix this:
```
apk add tzdata
cp - /usr/share/zoneinfo/Asia/Singapore /etc/localtime
```
obviously replacing the "Asia/Singapore" part with whatever applies for that individual user.

**Comment by drawingthesun** [comment]
I'm still getting utc time only and I can't seem to set the local time. I've tried the code above (https://github.com/ish-app/ish/issues/1086#issuecomment-1013810556) and also tried setting TZ environment variable, but I am not able to get date to understand local time.
