### ISSUE TITLE
Decimal display not working with light mode

### ISSUE THREAD

**Issue by dullbananas** [ish-app/ish#1418]

**Comment by 62f** [comment]
I must admit that I don't know the difference between a decimal point and a period. Please, enlighten me.

**Comment by dullbananas** [comment]
@62f they are the same character and "decimal point" only refers to usage in numbers.

I'm referring to the "decimal display" object in "outputs and labels" which displays a number with the decimal system, which uses digits 0 to 9.

**Comment by tbodt** [comment]
Don't understand what bug is being reported here. Maybe a screenshot would help?

**Comment by 62f** [comment]
<details>I expect the contributor could post an image showing that digits 0,1,2,3,4,5,6,7,8,9 display a null space on light mode rasters when they're part of a base-10 string whenever that numeric precision requires containing a decimal. I suppose each temporarily reappears when the cursor passes over them which is how they'd be identifiable;</details>

Also just discovered iOS itself seems incapable of displaying a Chinese ��

**Comment by dullbananas** [comment]
![image](https://user-images.githubusercontent.com/47706471/119435175-7a88c280-bcce-11eb-90e2-0a3486f49593.jpeg)

![image](https://user-images.githubusercontent.com/47706471/119435187-807ea380-bcce-11eb-9338-a63aa0751328.jpeg)

**Comment by 62f** [comment]
![image](https://user-images.githubusercontent.com/68332197/119438558-7ff60500-bcee-11eb-8901-29c6b60bb1c0.jpeg)![image](https://user-images.githubusercontent.com/68332197/119438582-8d12f400-bcee-11eb-936d-ad0dc4267182.jpeg)![image](https://user-images.githubusercontent.com/68332197/119438597-943a0200-bcee-11eb-82d3-9100ed542421.jpeg)![image](https://user-images.githubusercontent.com/68332197/119438603-99974c80-bcee-11eb-9661-e414648af6da.jpeg)
The text is still there, just invisible because its color is not being inverted.

**Comment by tbodt** [comment]
@dullbananas This doesn't look like iSH. Where did you capture the screenshot?

**Comment by dullbananas** [comment]
oop wrong repository. this is meant for circuitjs
