### ISSUE TITLE
Add Horizontal Navigation with alt/option + arrow keys

### ISSUE THREAD

**Issue by orphee-celui-qui-ne-sait-rien** [ish-app/ish#1530]
First of all, thank you for making this amazing tool. Now, to the point.

When I write a command with a large path or just very long, sometimes I make a mistake while typing, and usually it's very slow to just move with the keys of the keyboard (external keyboard + iPad), so it would be great to hold the option key to move faster through commands like on the macOS Terminal or a-Shell.

**Comment by saagarjha** [comment]
Most shells support readline shortcuts to navigate at the prompt; do shortcuts like ⌥B or ⌥F help?

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
Well, they work but they are slow, they only move the cursor 1 character, while what I was talking about with the ⌥ + arrows is moving the cursor trough entire words. Like this:


https://user-images.githubusercontent.com/79347623/129739417-3f97e242-9644-4118-99dc-dab5fd3e7685.mov

**Comment by rafal-1990** [comment]
I don't use a hardware keboard and there are bottons for `TAB`, `CTRL`, `ESC` and arrow keys.  
There is no button for `ALT` at all 😞. It would be great if an `ALT` button could be added. 
And maybe the option to hold these buttons (e.g. by tapping them twice in quick succession) could be added.

**Comment by MrApe** [comment]
+1 for this!

**Comment by jaclu** [comment]
> Well, they work but they are slow, they only move the cursor 1 character, while what I was talking about with the ⌥ + arrows is moving the cursor trough entire words. Like this:
> Enregistrement.d.ecran.le.2021-08-17.a.8.58.36.AM.mov

The only app setting that could prevent this from happening is if you are using an external keyboard, and in Settings-External Keyboard have Option->Meta unticked. Normally you should tick them all.

If that is set in case of external keyboard, or you are using the on-screen keyboard, when you experience this, you could try a fresh install.
First export your File System, then delete the app. Next, install the app again. This ensures you have a pristine app and a default filesystem. Then just type a few words at the root prompt and try alt/⌥  f/b to see if you can jump by word.

Once that is done, import your exported Filesystem , set it as "Boot From This Filesystem,   which reboots the kernel, change any app settings to your preference, and your back to your environment.

If this works as intended, the issue is most likely something you have unintentionally asked for either in app-settings or shell init or a combo. If you get stuck I will try to help to figure that one out.

Let us know if it is an issue on a pristine install, then it would be an important issue that needs to be looked into, I find it somewhat unlikely since I have reinstalled several times and often use quick jumping on the command line. But I guess the last time I reinstalled was in early July, so something could obviously have changed since.

**Comment by orphee-celui-qui-ne-sait-rien** [comment]
Hey, sorry for reporting back so much time later 😅... 
I've just tested what you said, and you were right, I had the app setting  "Option->Meta" unticked. It works fine on my external
