### ISSUE TITLE
R hangs after update

### ISSUE THREAD

**Issue by dcgrigsby** [ish-app/ish#1674]
After updating to Alpine v3.14 R hangs when run after displaying the usual, “ OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k”.  

iSH itself is not hung, as I can bring up the gear menu and see input in the terminal when I type.

On the theory that it was stuck trying to figure out something with the display, I tried running R and piping a script into it and the output to a file, but it still hung.

A Google search did not turn up other people having issues with R and this version of Alpine outside of iSH.

I have also ran tmux with top in one pane and R in the other; seems like there is a fatal crash, but nothing shows up in the iOS core dump directory.

Confirmed the behavior on another device, and after upgrading to Alpine 3.15 (which includes an updated R).   

Dmesg output:

8 stub syscall 383
35 stub syscall 383
35 stub syscall 383
35 stub syscall 383
35 stub syscall 383
35 stub syscall 383
35 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
38 stub syscall 383
38 stub syscall 383
38 stub syscall 383
38 stub syscall 383
38 stub syscall 383
38 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383
8 stub syscall 383

**Comment by dcgrigsby** [comment]
Tried running tmux, with top in one pane and then R in another.  It seems to kill the tty and hang both panels as it is unresponsive.  Looking through the core dumps under “Analytics and Improvements” there are a few iSH related files, but they do not appear to be coincident.

**Comment by dcgrigsby** [comment]
Upgraded a second devices and confirmed it hangs there too.

**Comment by dcgrigsby** [comment]
I downgraded to Alpine 3.13 and R works again.  I’d guess that the later versions are making a call to an operation that is not implemented in iSH’s emulator.  Something with its build flags, I would imagine,

**Comment by SugarRayLua** [comment]
I’ve not been using iSH for a while and went back to using it today and updated the repository and upgraded my installed packages and deleted my prior version of R (3.6) and tried to install the new R version (4.1.2) available on Alpine Linux 3.14. Unfortunately, after successfully installing R and R-dev, iSH suddenly became unusable due to the presence of the following errors that appear after every command I enter on the terminal:

“ Error relocating /lib/libssl.so.1.1: __gettimeofday_time64: symbol not found
Error relocating /lib/libssl.so.1.1: __time64: symbol not found
Error relocating /lib/libcrypto.so.1.1: __gmtime64_r: symbol not found
Error relocating /lib/libcrypto.so.1.1: __clock_gettime64: symbol not found
Error relocating /lib/libcrypto.so.1.1: __stat_time64: symbol not found
Error relocating /lib/libcrypto.so.1.1: __time64: symbol not found
Error relocating /lib/libcrypto.so.1.1: __dlsym_time64: symbol not found
Error relocating /lib/libcrypto.so.1.1: __fstat_time64: symbol not found
Error relocating /lib/libcrypto.so.1.1: __gettimeofday_time64: symbol not found
Error relocating /lib/libcrypto.so.1.1: __select_time64: symbol not found”

I’m not sure if this error is related to installing R or R-dev in Alpine 3.14 on the latest version of iSH and whether or not related to @dcgrigsby ‘s error above. I no longer use iSH on a regular basis, but when I do, I do like to use R and would appreciate any guidance from others if should do what @dcgrigsby did and go back to Alpine 3.13 and my previous R 3.6 version or hold tight for a while and wait for above errors to be troubleshot. 

Thanks!

**Comment by Mnpn** [comment]
Hi! We've recently released iSH 1.3, which should fix this problem with R. Please give it a try and file new issues if you encounter anything unexpected!
