### ISSUE TITLE
Is a true VM?

### ISSUE THREAD

**Issue by yap241986** [ish-app/ish#1729]
It is a real VM?

**Comment by saagarjha** [comment]
This question would probably be better asked as in [Discussions](https://github.com/ish-app/ish/discussions) or on our [Discord server](https://discord.gg/iSH), but no, iSH does not implement a VM in the traditional sense of a virtual machine. It reimplements a Linux kernel and an emulator rather than running the system through (hardware-assisted) virtualization.
