### ISSUE TITLE
lot of packages on alpine 3.18 require syscall 215 (setfsuid32)

### ISSUE THREAD

**Issue by filiphsps** [ish-app/ish#2198]
See `vim`, `nano`, `zsh` etc.

```
localhost:~# vim
Vim: Caught deadly signal SYS
Vim: Finished.
Bad system call
localhost:~# dmesg
104(vim) missing syscall 215
107(vim) missing syscall 215
109(vim) missing syscall 215
117(nano) missing syscall 215
121(zsh) missing syscall 215
123(nano) missing syscall 215
136(vim) missing syscall 215
localhost:~# 
```

**Comment by emkey1** [comment]
I can say from experience that doing always flagging unimplemented syscalls() as unimplemented and returning _ENOSYS fixes issues like this and doesn't cause many, if any problems.  The only time there could be an issue is if the code that invoked the unimplemented syscall() files to handle ENOSYS correctly.  I've yet to see that happen, though I'm sure there are cases where it does.  In any case, that seems less onerous then having a binary crash that would run fine otherwise.

**Comment by tbodt** [comment]
This is fixed by stubbing the syscall

**Comment by freebrowser1** [comment]
How do I stub the syscall ?
I get a 422 bad syscall when running Midnight Commander (mc).
