### ISSUE TITLE
Mount folders from other file providers

### ISSUE THREAD

**Issue by jckarter** [ish-app/ish#230]
It'd be awesome if you could open a folder in iCloud Drive, Working Copy, or other file providers and manipulate it directly from inside iSH as a mount point.

**Comment by tbodt** [comment]
What would the UI look like for this? Probably it would be invoked through a share sheet, but then how do you specify where you want the file/folder mounted?

**Comment by jckarter** [comment]
afaik it requires going through the open file UI to get access to a folder. In the (i) menu you could have a "Mount folder..." menu item that brings up the file picker. As far as where, maybe you could automatically map the folder under `/mnt/<folder name>`, or give the user another file picker to choose the mount location within the iSH filesystem.

**Comment by emkayonline** [comment]
A good example of a UI for The is in the app LibTerm:

Using the folder icon one can use the iOS file browser to choose a folder (Using 'select', then choosing the item, then 'open')

This then becomes the current directory (which I use then for processing the files in that folder).

For ish, rather than becoming the current directory, it would make sense to bookmark the selected folder as a /mnt point. (The apps Scriptable and Pythonista bookmark opened folders so that then can be mounted across sessions)

**Comment by tbodt** [comment]
This has been merged in now
