### ISSUE TITLE
Remove extra tty's from /etc/inittab?

### ISSUE THREAD

**Issue by emkey1** [ish-app/ish#868]
I've commented out tty2 through tty6 in /etc/inittab and restarted iSH and everything appears to work as expected.  I don't believe there is a way to get to those additional tty's so there really isn't any reason to have them running and removing them will free up a tiny bit of memory and resources.  

Just a suggestion but I wanted to document it here.

**Comment by emkey1** [comment]
Gotcha.  I'd claim that is breakage in Alpine.  I'm going to see if I can figure out why it is doing that and how to "fix" it since that might be useful information.

**Comment by tbodt** [comment]
It's quite hard to find a linux system (other than possibly some embedded kernels) that doesn't have /dev/tty0 through /dev/tty63.

**Comment by emkey1** [comment]
Interesting but not being able to disable them without side effects sure sounds like a bug, rather than a feature.

**Comment by emkey1** [comment]
Would it be possible for you to point me to a way to verify if the behavior with tty0  is occurring? I could test it on my Alpine VM I suppose but I'd be fiddling with the kernel boot options which aren't applicable in the case of iSH.

**Comment by tbodt** [comment]
Oh, I think I've misunderstood this issue the whole time. Nothing bad happens if you remove these ttys from inittab, but I don't want to modify inittab out of the box because I don't want to modify anything on the system if at all possible. When you're writing an emulator, and a program doesn't work, you fix the emulator, not the program.

The tty0 spam thing was what happened before I added fake ttys for tty1-6. init would spawn gettys in a loop which would keep failing and spam tty0 (where the stdout of init goes) with errors.

**Comment by emkey1** [comment]
Ah, I understand.  Thank you for the explanation.
