### ISSUE TITLE
64 bit

### ISSUE THREAD

**Issue by dullbananas** [ish-app/ish#908]
So apparently iSH emulates a 32 bit architecture. I ran `uname -m` and is says `i686` which is a 32 bit architecture. This needs to become 64 bit. 32 bit is becoming obsolete and might cause y2k38 bug

**Comment by saagarjha** [comment]
This issue is addressed in musl 1.2, which you can get right now by [switching to edge](https://wiki.alpinelinux.org/wiki/Edge). If Alpine Linux fails to ship this before 2038, we'll reopen this issue and consider other options.

**Comment by dullbananas** [comment]
tried that and `uname -m` is still `i686`

**Comment by saagarjha** [comment]
Right, but it solves the Year 2038 problem you were concerned about.

**Comment by dullbananas** [comment]
it also prevents me from installing elm compiler which has no 32 bit release

**Comment by saagarjha** [comment]
I hear that someone has [tried build Elm for 32-bit Debian](https://gist.github.com/rlefevre/8fcf368d9951137e9e810c06c111bba1); perhaps you might be able to follow those steps to compile it for iSH?

**Comment by xloem** [comment]
This issue is about the need for 64 bit support, not workarounds for specific examples of packages that no longer work easily on 32 bit. Every year, fewer things are compatible with 32 bit.

I understand a lot of work specific to i686 went into making this work at all, but it would be nice to have a place to discuss eventual next steps for 64 bit support.

**Comment by xloem** [comment]
Open issue at #1701
