### ISSUE TITLE
iSH filesystem does not appear in the iOS Files app if iSH is sideloaded via AltStore

### ISSUE THREAD

**Issue by econcz** [ish-app/ish#922]
With TestFlight everything works fine.

**Comment by 62f** [comment]
‘sideload’, used when something  bis already broken, in most cases sideloads are an attempt to rescue another copy of itself or a very similiar software package loaded into physically or logically-accessible memory space, common to both but not simply because a device is ‘jailbroken’.
So, is the procedure for reproducing thIs environment different from ordinary (non side-) loading by AltStore?
Is there a file system created by the iSH duplicate/original which already appears to be accessible, or is it AltStore Itself which is considered to be sideloaded with something else not mentioned, perhaps with Apple Store, into a non-jailbroken device?

**Comment by tbodt** [comment]
I fixed this upstream, it works since AltStore 1.4 beta 6.

**Comment by 62f** [comment]
Do you also develop on AltStore and the iOS files app, or where is ‘upstream of iSH’, exactly? One of the characteristics around the need to sideload software is the condition that at the there usually is no ‘upstream’...

**Comment by tbodt** [comment]
"upstream" refers to AltStore: https://github.com/rileytestut/AltStore/pull/346
