### ISSUE TITLE
apk install fails: network unreachable

### ISSUE THREAD

**Issue by jasonfma** [ish-app/ish#994]
When running the command to install apk in the App Store version I get this error:
```
wget -qO- http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86/apk-tools-static-2.10.5-r1....
...
wget: can't connect to remote host: Network unreachable
tar: invalid magic
tar: short read
tar: sbin/apk.static: not found in archive
```

Any ideas?

iPad Pro, iOS 14.0.1, iSH 1.0.1 (build 77)

**Comment by tbodt** [comment]
Does downloading this file in Safari work?

**Comment by jasonfma** [comment]
> Does downloading this file in Safari work?

Yeah it's working on iPad safari

**Comment by jasonfma** [comment]
Local network is enabled as well

![Image from iOS (17)](https://user-images.githubusercontent.com/7075070/97498539-a1923800-1929-11eb-9092-34d7c6cf8d8b.jpg)

**Comment by RashidFarhad** [comment]
-ash : apk: Not Found
iPhone 7Plus iOS 14.0.1 
how Fixed ?🤡
Thnx♥️

**Comment by jasonfma** [comment]
> -ash : apk: Not Found
> iPhone 7Plus iOS 14.0.1
> how Fixed ?🤡
> Thnx♥️

@RashidFarhad did you try this? https://github.com/ish-app/ish/wiki/Installing-apk-on-the-App-Store-Version

**Comment by StewAlexander-com** [comment]
Try the 32bit apk.static binary

Download it to the temp directory

Worked for me

**Comment by lijhello** [comment]
Maybe a faster and stable mirror site helps.
The following is a fast Chinese mirror.

(without the "rm" command part)

```
# ls
# wget -qO- http://mirrors.aliyun.com/alpine/v3.12/main/x86/apk-tools-static-2.10.5-r1.apk | tar -xz sbin/apk.static && ./sbin/apk.static add apk-tools 
OK: 353 MiB in 106 packages
# ls
sbin
# ls sbin/
apk.static
# 
```

**Comment by anglinb** [comment]
I’m running into the same issue that @jasonfma mentioned. I can’t actually reach activate the network for `ping` or `wget`. I have verified the common issues I would imagine I’d run into 

- I have “Local Network” enabled in Settings
- I am connected to the Internet 


I’m on an iPad Air (4th Generation) running version 14.1, iSH version 1.0.3 (Build 80)

**Comment by tbodt** [comment]
I'm not sure what's going on here. iSH just uses normal BSD socket functions, so if Safari is working then iSH should work too. There's been one similar problem in the past: apparently the Chinese version of iOS has a permission prompt for internet access, and just calling connect() won't trigger it. That was fixed by making a random network request on startup, though.

**Comment by lijhello** [comment]
Forgot to mention this. If the official repo is slow, try adding some more in this file. 

$ vi /etc/apk/repositories
#http://dl-cdn.alpinelinux.org/alpine/v3.12/main
#http://dl-cdn.alpinelinux.org/alpine/v3.12/community
https://mirrors.aliyun.com/alpine/v3.11/main
https://mirrors.aliyun.com/alpine/v3.11/community
$

**Comment by jasonfma** [comment]
> wget -qO - http://mirrors.aliyun.com/alpine/v3.12/main/x86/apk-tools-static-2.10.5-r1.apk | tar -xz sbin/apk.static && ./sbin/apk.static add apk-tools

This worked! Thank you!

**Comment by 62f** [comment]
I also suggest adding -c to wget, which aborts the download if the file is already completely downloaded and resumes in case of a disconnection. Unfortunately I am frequently firewalled from use of .cn-hosted repositories.
So why has this issue not yet been closed?

**Comment by 62f** [comment]
> -ash : apk: Not Found
> 
> iPhone 7Plus iOS 14.0.1 
> 
> how Fixed ?🤡
> 
> Thnx♥️

That ^ post is not related to this GitHub issue#, Thnx.

**Comment by 62f** [comment]
> I’m running into the same issue that @jasonfma mentioned. I can’t actually reach activate the network for `ping` or `wget`. I have verified the common issues I would imagine I’d run into 
> 
> 
> 
> - I have “Local Network” enabled in Settings
> 
> - I am connected to the Internet 
> 
> 
> 
> 
> 
> I’m on an iPad Air (4th Generation) running version 14.1, iSH version 1.0.3 (Build 80)

The latest iOS is v14.2 and iSH is v82.

**Comment by jasonfma** [comment]
> I also suggest adding -c to wget, which aborts the download if the file is already completely downloaded and resumes in case of a disconnection. Unfortunately I am frequently firewalled from use of .cn-hosted repositories.
> So why has this issue not yet been closed?

Sure I can close this. I thought maybe it would be good to keep it open until a root cause is found.

Please re-open if needed.

Thank you @lijhello for the workaround!

**Comment by 62f** [comment]
I wasn't asking for closure only suggesting but now that you ask: 
1) Your solution involved switching mirrors: not an iSH problem.
2) You're using a much older version of iSH.
3) The AppStore version of iSH now includes apk, and although an upgrade will not replace your repository list, upgrading would at least earn you the specific file you were requesting.
4) 'short read' AKA 'bad magic' is obviously a simple bad download. You thanked someone for their contribution, indicating that it was an acceptable solution to this.
5) No iOS analytics have been requested by any coder (which I am not), perhaps because there (was there?) not a full crash.
6) There are no tags in this issue# to indicate it needed further attention with the exception of an 'open' status, which in light of the other 5 reasons is deceptive.
